version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    image: app
    container_name: app
    restart: always
    volumes:
      - .:/var/www/html
    environment:

      # 資料庫
      DB_CONNECTION: mysql
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # 郵件
      MAIL_MAILER: smtp
      MAIL_SCHEME: null
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_USERNAME}
      MAIL_FROM_NAME: "會員中心服務"
    

    depends_on:
      - mysql_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql_db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-time-zone='+08:00' --skip-host-cache --skip-name-resolve

  nginx:
    image: nginx:stable
    container_name: member_center_nginx
    restart: always
    ports:
      - "8081:80"  
    volumes:
      - .:/var/www/html
      - ./docker/development/nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - app 

volumes:
  dbdata:
